[package]
name = "senzu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.0"
clap = "2.33.3"
rayon = "1.5.1"

# TODO: Add package description
# TODO: Add license
